<?php
$lang = [
    'home' => 'ഹോം',
    'products' => 'ഉൽപ്പന്നങ്ങൾ',
    'health_boxes' => 'ആരോഗ്യ പെട്ടികൾ',
    'chatbot' => 'പോഷകാഹാര ചാറ്റ്ബോട്ട്',
    'cart' => 'കാർട്ട്',
    'orders' => 'ഓർഡറുകൾ',
    'profile' => 'പ്രൊഫൈൽ',
    'login' => 'ലോഗിൻ',
    'signup' => 'സൈൻ അപ്പ്',
    'logout' => 'ലോഗ്ഔട്ട്',
    'farmer_dashboard' => 'കർഷക ഡാഷ്ബോർഡ്',
    'nutritionist_dashboard' => 'പോഷകാഹാര വിദഗ്ധ ഡാഷ്ബോർഡ്',
    'admin_dashboard' => 'അഡ്മിൻ ഡാഷ്ബോർഡ്',
    'add_to_cart' => 'കാർട്ടിലേക്ക് ചേർക്കുക',
    'add_to_favorites' => 'പ്രിയപ്പെട്ടവയിലേക്ക് ചേർക്കുക',
    'price' => 'വില',
    'quantity' => 'അളവ്',
    'total' => 'ആകെ',
    'checkout' => 'ചെക്കൗട്ട്',
    'place_order' => 'ഓർഡർ നൽകുക',
    'nutrition_coach' => 'പോഷകാഹാര കോച്ച്',
    'ask_nutrition_coach' => 'നിങ്ങളുടെ പോഷകാഹാര ചോദ്യം ചോദിക്കൂ...',
    'send' => 'അയയ്ക്കുക',
];
?>